/*
CREATED		27.8.2007 A.
MODIFIED		29.8.2007 A.
PROJECT		
MODEL		
COMPANY		
AUTHOR		
VERSION		
DATABASE		ORACLE 10G 
*/

ALTER TABLE "CATEGORIES" DROP CONSTRAINT "USERS_CATEGORIES"
/
ALTER TABLE "COMMENTS" DROP CONSTRAINT "USERS_COMMENTS"
/
ALTER TABLE "PHOTOS" DROP CONSTRAINT "CATEGORIES_PHOTOS"
/
ALTER TABLE "CATEGORIES" DROP CONSTRAINT "SELF"
/
ALTER TABLE "COMMENTS" DROP CONSTRAINT "PHOTOS_COMMENTS"
/
ALTER TABLE "USERS" DROP CONSTRAINT "USERS_USERNAME_UK"
/
ALTER TABLE "CATEGORIES" DROP CONSTRAINT "CATEGORIES_PATH_UK"
/
ALTER TABLE "PHOTOS" DROP CONSTRAINT "PHOTOS_PATH_UK"
/

DROP TABLE "COMMENTS"
/
DROP TABLE "PHOTOS"
/
DROP TABLE "CATEGORIES"
/
DROP TABLE "USERS"
/

DROP SEQUENCE SEQ_USERS
/
DROP SEQUENCE SEQ_CATEGORIES
/
DROP SEQUENCE SEQ_PHOTOS
/
DROP SEQUENCE SEQ_COMMENTS
/


-- CREATE TYPES SECTION

-- CREATE TABLES SECTION

CREATE TABLE "USERS" (
	"USER_ID" INTEGER NOT NULL ,
	"USERNAME" NVARCHAR2(20) NOT NULL ,
	"FIRST_NAME" NVARCHAR2(20) NOT NULL ,
	"LAST_NAME" NVARCHAR2(20) NOT NULL ,
	"PASSWORD" NVARCHAR2(20) NOT NULL ,
 CONSTRAINT "PK_USERS" PRIMARY KEY ("USER_ID") 
) 
/

CREATE TABLE "CATEGORIES" (
	"CATEGORY_ID" INTEGER NOT NULL ,
	"PARENT_CATEGORY_ID" INTEGER ,
	"USER_ID" INTEGER ,
	"CAT_NAME" NVARCHAR2(40) NOT NULL ,
	"PATH" NVARCHAR2(1000) NOT NULL ,
 CONSTRAINT "PK_CATEGORIES" PRIMARY KEY ("CATEGORY_ID") 
) 
/

CREATE TABLE "PHOTOS" (
	"PHOTO_ID" INTEGER NOT NULL ,
	"PH_NAME" NVARCHAR2(40) NOT NULL ,
	"PATH" NVARCHAR2(1000) NOT NULL ,
	"CATEGORY_ID" INTEGER ,
 CONSTRAINT "PK_PHOTOS" PRIMARY KEY ("PHOTO_ID") 
) 
/

CREATE TABLE "COMMENTS" (
	"COMMENT_ID" INTEGER NOT NULL ,
	"TEXT" NVARCHAR2(2000) NOT NULL ,
	"DATE" DATE NOT NULL ,
	"SENDER" NVARCHAR2(20) NOT NULL ,
	"PHOTO_ID" INTEGER NOT NULL ,
	"USER_ID" INTEGER,
 CONSTRAINT "PK_COMMENTS" PRIMARY KEY ("COMMENT_ID") 
) 
/

-- CREATE ALTERNATE KEYS SECTION

-- CREATE INDEXES SECTION

-- CREATE SECTION FOR PKS, AKS AND UNIQUE CONSTRAINTS, WHICH HAVE TO BE GENERATED AFTER INDEXES

ALTER TABLE USERS ADD CONSTRAINT USERS_USERNAME_UK UNIQUE ("USERNAME") ENABLE
/

ALTER TABLE CATEGORIES ADD CONSTRAINT CATEGORIES_PATH_UK UNIQUE ("PATH") ENABLE
/

ALTER TABLE PHOTOS ADD CONSTRAINT PHOTOS_PATH_UK UNIQUE ("PATH") ENABLE
/

-- CREATE FOREIGN KEYS SECTION

ALTER TABLE "CATEGORIES" ADD CONSTRAINT "USERS_CATEGORIES" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("USER_ID") 
/

ALTER TABLE "COMMENTS" ADD CONSTRAINT "USERS_COMMENTS" FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("USER_ID") 
/

ALTER TABLE "PHOTOS" ADD CONSTRAINT "CATEGORIES_PHOTOS" FOREIGN KEY ("CATEGORY_ID") REFERENCES "CATEGORIES" ("CATEGORY_ID") 
/

ALTER TABLE "CATEGORIES" ADD CONSTRAINT "SELF" FOREIGN KEY ("PARENT_CATEGORY_ID") REFERENCES "CATEGORIES" ("CATEGORY_ID") 
/

ALTER TABLE "COMMENTS" ADD CONSTRAINT "PHOTOS_COMMENTS" FOREIGN KEY ("PHOTO_ID") REFERENCES "PHOTOS" ("PHOTO_ID") 
/

-- CREATE OBJECT TABLES SECTION

-- CREATE XMLTYPE TABLES SECTION

-- CREATE PROCEDURES SECTION

-- CREATE FUNCTIONS SECTION

-- CREATE VIEWS SECTION

-- CREATE SEQUENCES SECTION

CREATE SEQUENCE SEQ_USERS INCREMENT BY 1 START WITH 10000;
/
CREATE SEQUENCE SEQ_CATEGORIES INCREMENT BY 1 START WITH 10000;
/
CREATE SEQUENCE SEQ_PHOTOS INCREMENT BY 1 START WITH 10000;
/
CREATE SEQUENCE SEQ_COMMENTS INCREMENT BY 1 START WITH 10000;
/


-- CREATE TRIGGERS FROM REFERENTIAL INTEGRITY SECTION

-- CREATE USER TRIGGERS SECTION

-- CREATE PACKAGES SECTION

-- CREATE SYNONYMS SECTION

-- CREATE ROLES SECTION

-- USERS PERMISSIONS TO ROLES SECTION

-- ROLES PERMISSIONS SECTION
/* ROLES PERMISSIONS */

-- USER PERMISSIONS SECTION
/* USERS PERMISSIONS */

-- CREATE TABLE COMMENTS SECTION

-- CREATE ATTRIBUTE COMMENTS SECTION

-- AFTER SECTION


